[package]
name = "black_scholes"
version = "0.1.0"
edition = "2021"
authors = ["gigi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16.0"
round = "0.1.0"
